on: [push]
name: Build & deploy

jobs:
  build:
    name: Build & deploy
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm ci
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
      - name: Build
        run: npm run build
        env:
          VITE_API_URL: https://api-djabolo.${{ secrets.MACHINE_HOST }}
      - name: Run SSH Agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.MACHINE_SSH_KEY }}
      - name: Add server to known hosts
        run: mkdir -p ~/.ssh; ssh-keyscan -p ${{ secrets.MACHINE_SSH_PORT }} ${{ secrets.MACHINE_HOST }} >> ~/.ssh/known_hosts
      - name: Copy to server
        run: scp -P ${{ secrets.MACHINE_SSH_PORT }} -r ${{ github.workspace }}/dist/* runs@${{ secrets.MACHINE_HOST }}:~/web

